### ISSUE TITLE
How to make map fullscreen in the bs4Dash::dashboarBody?

### ISSUE THREAD

**Issue by Camil88** [RinteRface/bs4Dash#159]
Hello, I'm struggling with this issue which was not an issue in shinydashboardPlus. I want to make mapbox/leaflet map full in dashboardBody. I'm using bs4Dash libraray (downloaded from GitHub). Crucial R and CSS code is here:

`
bs4Dash::dashboardBody(
   mapboxer::mapboxerOutput("map")
)
`

and  **CSS:**
`
#map {
  height: calc(100vh - 57px) !important;
  width: calc(100vw - 73.594px) !important;
}
`
`
.content-wrapper>.content {
  padding: 0 !important;
} 
`

With this code, when you run an app, map will fill the whole body - so it works fine. But when you open (collapse) sidebar the whole map moves to the right and scroll bar aapears on the bottom and on the right of the window. As I said, it diddn't happen in shinydashboardPlus and I used the same CSS code.

**Below: map on start, before opening sidebar**

![obraz](https://user-images.githubusercontent.com/57962280/105493091-34d4d280-5cb9-11eb-8764-df41e39ffd39.png)

**Below: map after opening sidebar**

![obraz](https://user-images.githubusercontent.com/57962280/105493303-7feee580-5cb9-11eb-8267-0e2042946e01.png)

When I use only this CSS:

`
#map {
  height: calc(100vh - 57px) !important;
}
`
Then when I open sidebar the scroll bar disappears - the issue is that then I can see strange margin on the right side of the map and can't remove it.

![obraz](https://user-images.githubusercontent.com/57962280/105498672-c136c380-5cc0-11eb-9e67-53cc65f450fb.png)

I tried many css combinations but none of them work.

**Comment by DivadNojnarg** [comment]
Could you show me the whole code, so that I can reproduce on my side? Thanks

**Comment by Camil88** [comment]
Sure, I've just added my simple demo app to respository, it's here: https://github.com/Camil88/Shiny_App

I've noticed some issues, don't know how to solve it:
1. When I add `skin="dark"` to dashboardHeader then header's skin does not change. However, icons change their color to transparent (white?)
2. I commented `preloader=..` in my code because it can't stop loading page even thought `duration` is set to 5, so iy should stop loading after 5 seconds and show the page.
3. Map is almost fullscreen  except for a few pixels margin on the very right side of the page. And as I described in the post above - when I add `width: calc(100vw - 73.594px) !important;` to CSS then map is fullsize on page start but when sidebar is open then scroll bar appears (you can see it on screens above). Notice I'm using `mapbox` here. By the way, the problem doesn't exist when I use `shinydashboardPlus ` package, it works fine. 
Interesting thing is that when I use `leaflet` map then it's fullsize on page start (I also added leaflet code to my test app, you can uncomment it and see how it works). However I also noticed something in `leaflet` - when you open/close sidebar then map moves abruptly/jumps somehow, it's strange. So how can I make `mapbox` fullsize in body?
4. `customArea` doesn't work in my app, what's wrong with it? Honestly I copied this chunk of code from your demo app, here it's not working.
5. I noticed that switching to dark-mode on page start is only possible using some js code. Or maybe there's any other option to set dark-mode as default when page starts?
6. Code added to repository is a single app.R, don't know if it makes so much difference but I write my app using `golem` package (and yes, I added all required libraries to my project).

Thanks for all answers in advance. I'd like to use bs4Dash since it looks nice and is functional but I need to overcome some issues like those above to move forward.

**Comment by DivadNojnarg** [comment]
Hi,

Here is my solution:

1. Download latest `{bs4Dash}` from github: `remotes::install_github("RinteRface/bs4Dash")`
2. Don't worry about `skin = "dark"` in `dashboardHeader`. `{bs4Dash}` sets the good value based on the current theme. 
3. It's quite strange about the preloader. I was not able to reproduce your issue.
4. I added inline CSS to the `dashboardBody` to overwrite that provided by `{bs4Dash}`, so that there is no padding around the leaflet element `"padding: 0px 0px !important"`.
5. customArea were broken. Thanks for the report, I fixed it. 
6. Now when `dark` is TRUE, the switch is activated so that the dark theme is automatically applied. No need for custom JS code. Thanks for the report.

```r
library(shiny)
library(bs4Dash)
library(leaflet)
library(mapboxer)
library(waiter)

Sys.setenv(MAPBOX_API_TOKEN = "pk.eyJ1IjoiaHdsIiwiYSI6ImNramJxY2YxcDV2YXoyeW40YXlvbmUyazQifQ.7HBEvMyrAnVpkKO7MNH7ww")

bodyTag <- dashboardBody(
  tags$head(
    tags$style(
      "
        #map {
          height: calc(100vh - 57px) !important;
        
        }

        .card:nth-of-type(1) {
          margin-top: 30px;
          position: absolute;
          z-index: 1;
          opacity: 0.9;
          width: 280px;
          
        }

        #burger, #burger:hover {
          font-size: medium;
          background-color: transparent;
          border-color: transparent;
          margin-left: 8px;
          margin-top: 10px;         
        }

        #burger:focus {
          outline: 0;
        }
        "
    )
  ),
  
  tabItems(
    tabItem(
      tabName = "live",
      box(
        title = "LIVE",
        id = "panelLeft",
        height = 450,
        collapsible = TRUE
      )
    ),
    
    
    tabItem(
      tabName = "drivers",
      box(
        title = "Drivers",
        id = "panelLeft",
        height = 450,
        collapsible = TRUE
      )
    )
  ),
  
  #mapboxerOutput("map")
  leafletOutput("map")
)

bodyTag$children[[1]]$attribs$style <- "padding: 0px 0px !important" 


ui <- dashboardPage(
  dark = TRUE,
  #preloader = list(
  #  waiter = list(html = tagList(spin_1(), "Loading ..."), color = "#343a40"),
  #  duration = 5
  #),
  header = dashboardHeader(
    title = h5("DEMO app"),

    rightUi = tagList(
      dropdownMenu(
        type = "notifications",
        badgeStatus = "danger",
        icon = icon("bell"),
        notificationItem(
          icon = icon("bell"),
          status = "info",
          "XYZ"
        ),
        notificationItem(
          icon = icon("warning"),
          status = "danger",
          "XYZ"
        )
      ),

      dropdownMenu(
        type = "messages",
        badgeStatus = "warning",
        icon = icon("envelope"),
        messageItem("Legal",
          "XYZ",
          time = "15 mins"
        ),
        messageItem("RRR",
          "XYZ",
          time = "5 mins"
        )
      )
    )
  ),


  sidebar = dashboardSidebar(
    fixed = TRUE,
    collapsed = TRUE,
    expandOnHover = FALSE,
    status = "purple",

    customArea = fluidRow(
      actionButton(
        inputId = "myAppButton",
        label = NULL,
        icon = icon("users"),
        width = NULL,
        status = "primary",
        style = "margin: auto",
        dashboardBadge(1, color = "danger")
      )
    ),

    sidebarMenu(
      id = "sidebarID",
      menuItem("LIVE", tabName = "live", icon = icon("circle")),
      menuItem("Drivers", tabName = "drivers", icon = icon("user-friends"))
    )
  ),
  body = bodyTag
)



server <- function(input, output) {
  observeEvent(input$sidebarID, {
    updateBox("panelLeft", action = "toggle")
  })


  #output$map <- renderMapboxer({
  #  mapboxer(
  #    style = basemaps$Mapbox$light_v10,
  #    center = c(-73.98928, 40.75042),
  #    zoom = 6
  #  ) %>%
  #    htmlwidgets::onRender("
  #  function(el, x) {
  #    console.log(x);
  #  }
  #")
  #}) 

  output$map <- renderLeaflet({
      leaflet() %>%
          setView(lng = -73.98928, lat = 40.75042, zoom = 6) %>%
          addProviderTiles("CartoDB.Positron") 
      })
}


shinyApp(ui = ui, server = server)
```

**Comment by Camil88** [comment]
Thanks for your comments and enhancements. I downloaded latest version and it works properly. When it comes to preloader still don't know, it can't stop loading the page. As for map - yes, it works fine for leaflet but not for mapbox. I uncommented the code above (referring to mapbox) and still there is a kind of margin on the right side, seems like map is not resized to 100% of content. However, thanks for help!

**Comment by Camil88** [comment]
I've found a solution for making mapbox fullsize. I added to CSS:

`
#map {
  height: calc(100vh - 57px) !important; 
  width: calc(100vw - 73.594px) !important; 
}
`
`
.wrapper {
    overflow-x: hidden;
    overflow-y: auto;
}
`

thanks to this code no scroll bars appear on the bottom and on the right side and everything works smoothly. I've noticed that `.wrapper' style options were default in `shinydashboardPlus` , I needed to add them to `bs4Dash` using this CSS.
